#!/usr/bin/env bash
#
# One-command local development environment.
#
#   ./dev.sh                  start database, API and web app
#   ./dev.sh stop             stop the database container
#   ./dev.sh reset            delete the database volume and start fresh
#   ./dev.sh migration <Name> create an EF Core migration
#
# No credential is hardcoded here. On first run this generates .env.dev
# (gitignored) with random local-only values and reuses it afterwards.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$ROOT/RentalManagementSystem/Backend/RentalManagement.Api"
WEB_DIR="$ROOT/RentalManagementSystem/Frontend"
ENV_FILE="$ROOT/.env.dev"

API_PORT="5152"
WEB_PORT="3000"

log() { printf '\033[0;36m==>\033[0m %s\n' "$1"; }
die() { printf '\033[0;31mError:\033[0m %s\n' "$1" >&2; exit 1; }

compose() {
  if docker compose version >/dev/null 2>&1; then
    docker compose "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    docker-compose "$@"
  else
    die "Docker Compose not found. Install Docker Desktop: https://docs.docker.com/get-docker/"
  fi
}

require() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required but not installed.${2:+ $2}"
}

# --- Local credentials -----------------------------------------------------
# Generated once, kept out of git. Local development only — these values have no
# bearing on any deployed environment. See DEPLOYMENT.md for real deployments.
if [ ! -f "$ENV_FILE" ]; then
  require openssl
  log "Generating $ENV_FILE (first run)"
  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by dev.sh — local development only, never committed.
# Delete this file to regenerate. './dev.sh reset' is needed after that,
# because the database keeps the password it was first created with.
POSTGRES_USER=admin
POSTGRES_PASSWORD=$(openssl rand -hex 16)
POSTGRES_DB=rental_management
POSTGRES_PORT=5433
JWT_SECRET_KEY=$(openssl rand -base64 48 | tr -d '\n')
SEED_ADMIN_PASSWORD=Dev$(openssl rand -hex 6)aA1
EOF
fi

set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a

export DATABASE_URL="Host=localhost;Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true"
export ASPNETCORE_ENVIRONMENT="Development"
export ASPNETCORE_URLS="http://localhost:${API_PORT}"
export FRONTEND_URL="http://localhost:${WEB_PORT}"

# The API targets net9.0. Allow it to run on a newer runtime so a machine with
# only .NET 10 installed still works.
export DOTNET_ROLL_FORWARD="LatestMajor"

# Both names are read by the frontend, depending on the module.
export VITE_API_BASE_URL="http://localhost:${API_PORT}/api"
export VITE_API_URL="$VITE_API_BASE_URL"

# --- Subcommands -----------------------------------------------------------
case "${1:-start}" in
  stop)
    log "Stopping database"
    (cd "$ROOT" && compose down)
    exit 0
    ;;
  migration)
    [ -n "${2:-}" ] || die "Usage: ./dev.sh migration <Name>"
    require dotnet
    log "Creating migration '$2'"
    (cd "$API_DIR" && dotnet ef migrations add "$2")
    log "Review the generated files in Migrations/, then commit them."
    exit 0
    ;;
  reset)
    log "Removing database volume"
    (cd "$ROOT" && compose down -v)
    ;;
  start) ;;
  *) die "Unknown command '$1'. Use: start | stop | reset | migration <Name>" ;;
esac

# --- Preflight -------------------------------------------------------------
require docker "See https://docs.docker.com/get-docker/"
require dotnet "See https://dotnet.microsoft.com/download/dotnet/9.0"
require npm    "See https://nodejs.org/"

docker info >/dev/null 2>&1 || die "Docker is installed but not running. Start Docker Desktop and retry."

# --- Database --------------------------------------------------------------
log "Starting PostgreSQL on port ${POSTGRES_PORT}"
(cd "$ROOT" && compose up -d postgres)

log "Waiting for PostgreSQL to accept connections"
for _ in $(seq 1 60); do
  if (cd "$ROOT" && compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1); then
    break
  fi
  sleep 1
done
(cd "$ROOT" && compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1) \
  || die "PostgreSQL did not become ready in time. Check: docker compose logs postgres"

# --- Frontend dependencies -------------------------------------------------
if [ ! -d "$WEB_DIR/node_modules" ]; then
  log "Installing frontend dependencies"
  (cd "$WEB_DIR" && npm ci)
fi

# --- Run -------------------------------------------------------------------
# The API applies EF migrations and seeds the admin user on startup.
cleanup() {
  log "Shutting down"
  [ -n "${API_PID:-}" ] && kill "$API_PID" 2>/dev/null || true
  [ -n "${WEB_PID:-}" ] && kill "$WEB_PID" 2>/dev/null || true
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

log "Starting API on ${ASPNETCORE_URLS}"
(cd "$API_DIR" && dotnet run --no-launch-profile) &
API_PID=$!

log "Starting web app on ${FRONTEND_URL}"
(cd "$WEB_DIR" && npm run dev -- --port "$WEB_PORT") &
WEB_PID=$!

cat <<EOF

  API      ${ASPNETCORE_URLS}
  Swagger  ${ASPNETCORE_URLS}/swagger
  Web      ${FRONTEND_URL}

  Sign in  admin@rentalmanagement.com
           ${SEED_ADMIN_PASSWORD}
           (also in .env.dev)

  Ctrl-C to stop. Database keeps running; './dev.sh stop' shuts it down.

EOF

wait -n "$API_PID" "$WEB_PID" 2>/dev/null || wait
